In [1]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []
for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index]+list_three[index])
print(list_sum)

[2, 12, 36]


In [10]:
import numpy as np
array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [11]:
sample_array = np.array([1,2,3])

In [13]:
print(np.power(sample_array,4))

[ 1 16 81]


In [14]:
print(np.negative(sample_array))

[-1 -2 -3]


In [16]:
print(np.exp(sample_array))

[ 2.71828183  7.3890561  20.08553692]


In [18]:
print(np.power(np.negative(sample_array),3))

[ -1  -8 -27]


In [19]:
print(np.log(sample_array))

[0.         0.69314718 1.09861229]


In [20]:
print(np.sin(sample_array))

[0.84147098 0.90929743 0.14112001]


In [42]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)
multi_array = np.array([x,y,z], dtype = np.int64)
print(multi_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
print(multi_array.shape)

(3, 3)


In [44]:
w = np.linspace(1,10,50, False)
print(w)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


In [45]:
b = np.arange(1,30,3)
print(b)

[ 1  4  7 10 13 16 19 22 25 28]


In [46]:
print(multi_array[2,2])

8


In [47]:
print(multi_array.dtype)

int64


In [48]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [51]:
print(x[2:7])

[3 4 5 6 7]


In [52]:
print(x[2:7:2])

[3 5 7]


In [53]:
print(x[:7])

[1 2 3 4 5 6 7]


In [54]:
print(x[2:])

[3 4 5 6 7 8 9]


In [62]:
x = np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [64]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
print(x[2,1])

7


In [66]:
x = np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [67]:
print(x[1,1,1])

10


In [78]:
print(x[1,:2,:3:2])

[[ 6  8]
 [ 9 11]]


In [85]:
comparison_operation = x > 5
print(x[x<15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [86]:
print(x.max())

17


In [87]:
print(x.min())

0


In [88]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [89]:
ravelled_array = x.ravel()
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]


In [92]:
flatenned_array = x.flatten()
flatenned_array[2] = 1000000;
print(flatenned_array)
print(x)

[      0       1 1000000       3       4       5       6       7       8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
ravelled_array[2] = 100000
print(ravelled_array)
print(x)

[     0      1 100000      3      4      5      6      7      8]
[[     0      1 100000]
 [     3      4      5]
 [     6      7      8]]


In [98]:
y = np.arange(9)
y.shape = [3,3]
print(y)
print(y.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [99]:
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [100]:
print(np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [106]:
print(np.zeros((6,6), dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [107]:
print(np.ones((5,5),dtype = int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [108]:
print(np.eye((3),dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [112]:
print(np.random.rand(4,4))

[[0.96823979 0.28387995 0.34335588 0.12472784]
 [0.93821617 0.21146773 0.75909962 0.87858387]
 [0.23684627 0.35023753 0.10519506 0.87370908]
 [0.16424361 0.77790995 0.42304128 0.49304185]]


In [114]:
mat_a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
print(mat_a)

[[0 3 5]
 [5 5 2]]


In [115]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
print(mat_b)

[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [116]:
print(mat_a*mat_b)

[[ 29 -16]
 [ 38   6]]


In [117]:
product = np.matmul(mat_a,mat_b)
print(product)

[[ 29 -16]
 [ 38   6]]


In [118]:
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]


In [130]:
x = np.arange(4).reshape(2,2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [128]:
y = np.arange(4,8).reshape(2,2)
print(y)

[[4 5]
 [6 7]]


In [131]:
z = np.hstack((x,y))
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [132]:
x = np.arange(8).reshape(4,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [133]:
y = np.arange(8).reshape(4,2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [134]:
z = np.vstack((x,y))
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [135]:
print(z.shape)

(8, 2)


In [137]:
w = np.concatenate((x,y),axis = 1)
print(w)

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [138]:
w = np.concatenate((x,y),axis = 0)
print(w)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [139]:
z = np.vstack((x,y))
print(z==w)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [143]:
y = x * 2
print(y)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


In [141]:
depth_stack = np.dstack((x,y))
print(depth_stack)

[[[ 0  0]
  [ 1  2]]

 [[ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]]]


In [142]:
print(depth_stack.shape)

(4, 2, 2)


In [145]:
print(np.column_stack((x,y)) == np.hstack((x,y)))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [146]:
print(np.row_stack((x,y)) == np.vstack((x,y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
